---
- name: docker.io apt key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
- name: docker.io repository
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
- name: install docker defaults
  copy:
    content: "DOCKER_OPTS=\"{{ docker_opts }}\""
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0744
  notify:
    - reload docker
- name: install docker
  apt:
    name: "lxc-docker={{ version }}"
