---
# - name: docker.io apt key
#   apt_key:
#     id: "{{ apt_key_sig }}"
#     #url: "{{ apt_key_url }}"
#     keyserver: http://keyserver.ubuntu.com/
#     state: present

- shell: "curl -sSL {{ apt_key_url }} | gpg --import"
- name: docker.io repository
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present

- name: install docker defaults
  copy:
    content: "DOCKER_OPTS=\"{{ docker_opts }}\""
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0744
  notify:
    - reload docker

- name: install docker
  apt:
    name: "docker-ce"
    force: yes

- name: ensure docker is running
  service:
    name: docker
    enabled: yes
    state: started
